### 배열 확장
- hstack : horizental stack
- vstack : vertical stack
- dstack : depth stack
- stack
- r_
- c_
- tile

In [1]:
import numpy as np

In [2]:
def aryInfo(arr) :
    print("type : {}".format(type(arr)))
    print("shape : {} , dimension : {} , dtype : {}".format(arr.shape , arr.ndim, arr.dtype))
    print("Array's Data : \n" , arr)

In [7]:
# hstack : col이 늘어나는 것이기 때문에 반드시 행의 숫자가 똑같아야만 한다.
h_ary_01 = np.ones((2,3))
aryInfo(h_ary_01)

type : <class 'numpy.ndarray'>
shape : (2, 3) , dimension : 2 , dtype : float64
Array's Data : 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# astype() : 타입의 변화를 줄 때 사용하는 방법 중 하나, dtype=''도 있다. 
re_type = h_ary_01.astype(np.int32)
aryInfo(re_type)

type : <class 'numpy.ndarray'>
shape : (2, 3) , dimension : 2 , dtype : int32
Array's Data : 
 [[1 1 1]
 [1 1 1]]


In [11]:
h_ary_02 = np.zeros((2,3))
aryInfo(h_ary_02)

type : <class 'numpy.ndarray'>
shape : (2, 3) , dimension : 2 , dtype : float64
Array's Data : 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
np.hstack([h_ary_01, h_ary_02])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [ ]:
# vstack : row가 늘어나는 것이기 때문에 반드시 열의 숫자가 똑같아야만 한다.

In [14]:
np.vstack([h_ary_01, h_ary_02]) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# dstack : 깊이가 늘어나는 것
d_ary_01 = np.ones((3,4))
print(d_ary_01)
d_ary_02 = np.zeros((3,4))
print(d_ary_02)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
# (3 * 4) --> (3 * 4 * 2)
np.dstack([d_ary_01, d_ary_02])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [21]:
aryInfo(np.dstack([d_ary_01, d_ary_02]))

type : <class 'numpy.ndarray'>
shape : (3, 4, 2) , dimension : 3 , dtype : float64
Array's Data : 
 [[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]


In [29]:
# stack : 행과 열의 갯수가 똑같아야 한다.
# (3 * 4) -> (2 * 3 * 4)
s_ary = np.stack([d_ary_01, d_ary_02], axis=0)
aryInfo(s_ary)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4) , dimension : 3 , dtype : float64
Array's Data : 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [30]:
# (3 * 4) -> (3 * 2 * 4)
s_ary = np.stack([d_ary_01, d_ary_02], axis=1)
aryInfo(s_ary)

type : <class 'numpy.ndarray'>
shape : (3, 2, 4) , dimension : 3 , dtype : float64
Array's Data : 
 [[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]


In [31]:
# (3 * 4) -> (3 * 4 * 2)
s_ary = np.stack([d_ary_01, d_ary_02], axis=2)
aryInfo(s_ary)

type : <class 'numpy.ndarray'>
shape : (3, 4, 2) , dimension : 3 , dtype : float64
Array's Data : 
 [[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]


In [32]:
np.r_[ np.array([1,2,3]) , np.array([4,5,6])] # 1차원 벡터 두 개를 row bind

array([1, 2, 3, 4, 5, 6])

In [33]:
np.c_[ np.array([1,2,3]) , np.array([4,5,6])] # 1차원 벡터 두 개를 col bind

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
np.r_[ d_ary_01 , d_ary_02 ]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.c_[ d_ary_01 , d_ary_02 ]

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

- tile : 동일한 배열을 반복하여 연결시킬 때 사용한다.

In [5]:
t_ary = np.array([[1,2,3], [4,5,6]])

In [6]:
np.tile(t_ary , 3 )

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [7]:
np.tile(t_ary, (3,2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [15]:
a = np.zeros([3,3])
b = np.ones([3,2])
ab = np.hstack([a, b])
ab

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [17]:
c

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [3]:
a = np.zeros([3,3])
b = np.ones([3,2])
ab = np.hstack([a, b])
c = np.array([[10,20,30,40,50], [60,70,80,90,100], [110,120,130,140,150]])
abc = np.vstack([ab, c])
np.tile(abc, (2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [3]:
x = np.zeros((3,3))
print(aryInfo(x))
y = np.ones((3,2))
print(aryInfo(y))
xy = np.hstack([x,y])
print(aryInfo(xy))
z = np.arange(10, 160, 10).reshape((3,5))
print(aryInfo(z))
xyz = np.vstack([xy, z])
print(aryInfo(xyz))
answer = np.tile(xyz, (2,1))
print(answer)

type : <class 'numpy.ndarray'>
shape : (3, 3) , dimension : 2 , dtype : float64
Array's Data : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
None
type : <class 'numpy.ndarray'>
shape : (3, 2) , dimension : 2 , dtype : float64
Array's Data : 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
None
type : <class 'numpy.ndarray'>
shape : (3, 5) , dimension : 2 , dtype : float64
Array's Data : 
 [[0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]]
None
type : <class 'numpy.ndarray'>
shape : (3, 5) , dimension : 2 , dtype : int32
Array's Data : 
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]
None
type : <class 'numpy.ndarray'>
shape : (6, 5) , dimension : 2 , dtype : float64
Array's Data : 
 [[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]
None
[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90.

### delete()
- 행과 열을 삭제 : axis
- row data는 변경하지 않고 새로운 배열을 리턴

In [4]:
ary = np.random.randint(0, 10, (3, 4))
aryInfo(ary)

type : <class 'numpy.ndarray'>
shape : (3, 4) , dimension : 2 , dtype : int32
Array's Data : 
 [[0 4 5 3]
 [5 0 4 3]
 [8 2 7 7]]


In [5]:
result = np.delete(ary, 0, axis = 1)
aryInfo(result)

type : <class 'numpy.ndarray'>
shape : (3, 3) , dimension : 2 , dtype : int32
Array's Data : 
 [[4 5 3]
 [0 4 3]
 [2 7 7]]
