# Numpy

## 학습목표 : 배열과 리스트의 차이점을 배워보자

In [7]:
import numpy as np

In [8]:
np.__version__

'1.19.2'

### 배열 자료구조 클래스인 ndarray - vector , matrix
### 배열의 차원과 크기 - ndim , shape

In [12]:
def aryInfo(arr) :
    print("type : {}".format(type(arr)))
    print("shape : {} , dimension : {} , dtype : {}".format(arr.shape , arr.ndim, arr.dtype))
    print("Array's Data : \n" , arr)

### 1차원 배열 만들기

In [13]:
ary = np.array([0,1,2,3,4,5,6,7,8,9])
ary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
aryInfo(ary)

type : <class 'numpy.ndarray'>
shape : (10,) , dimension : 1 , dtype : int32
Array's Data : 
 [0 1 2 3 4 5 6 7 8 9]


### Vectorized Operation( 벡터화 연산 )

In [23]:
data = [0,1,2,3,4,5,6,7,8,9]
data * 2 # 리스트 자체로는 계산이 불가능하다. list comprehension 이나 for loop 활용해야 한다. 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
# for 문을 활용한 의도한 계산법
answer = []
for d in data :
    answer.append(d * 2)
print(answer, type(data))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18] <class 'list'>


In [28]:
# list comprehension을 이용한 계싼법
data2 = [i*2 for i in data]
print(data2, type(data2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18] <class 'list'>


In [27]:
# 벡터화 연산을 이용한 빠른 연산이 가능하다. 반복을 사용했을 때 보다 수행의 속도가 빠르고 메모리 절감!
x = np.array(data)
x * 2
print(x, type(x))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


### 비교연산, 논리연산

In [33]:
oneAry = np.array([1,2,3])
twoAry = np.array([10,20,30])
oneAry + twoAry

array([11, 22, 33])

In [34]:
oneAry + twoAry * 2

array([21, 42, 63])

In [35]:
# boolean 형식으로 값이 들어있는지 확인가능 boolean masking
oneAry == 2

array([False,  True, False])

In [36]:
twoAry > 10

array([False,  True,  True])

In [37]:
(oneAry == 2) & (twoAry > 10)

array([False,  True, False])

### 2차원 배열 (행렬, matrix)

In [38]:
matrix = np.array([[0,1,2], [3,4,5]])
aryInfo(matrix)

type : <class 'numpy.ndarray'>
shape : (2, 3) , dimension : 2 , dtype : int32
Array's Data : 
 [[0 1 2]
 [3 4 5]]


In [40]:
print('행의 갯수 : ', len(matrix))
print('열의 갯수 : ', len(matrix[0]))

행의 갯수 :  2
열의 갯수 :  3


### 3차원 배열

In [46]:
threeDimAry = np.array([[[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12]],
                        [[11,12,13,14],
                        [15,16,17,18],
                        [19,20,21,22]]])

In [47]:
aryInfo(threeDimAry)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4) , dimension : 3 , dtype : int32
Array's Data : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [51]:
print( len(threeDimAry) , len(threeDimAry[0]) , len(threeDimAry[0][0]))

2 3 4


In [55]:
x = np.array([100, 'hello', 3.14])
x
# <U11 type은 문자열이라고 생각하면 된다.
print('array {}'.format(x))
print('type {}'.format(type(x)))
print('x.type {}'.format(x.dtype))
print('x[0] type {}'.format(type(x[0])))

array ['100' 'hello' '3.14']
type <class 'numpy.ndarray'>
x.type <U11
x[0] type <class 'numpy.str_'>


### indexing를 알아보자

In [54]:
data = np.array([0,1,2,3,4,5])
aryInfo(data)

type : <class 'numpy.ndarray'>
shape : (6,) , dimension : 1 , dtype : int32
Array's Data : 
 [0 1 2 3 4 5]


In [56]:
data[2]

2

In [58]:
data[-1]

5

In [59]:
matrix = np.array([[0,1,2], [3,4,5]])
aryInfo(matrix)

type : <class 'numpy.ndarray'>
shape : (2, 3) , dimension : 2 , dtype : int32
Array's Data : 
 [[0 1 2]
 [3 4 5]]


In [74]:
matrix[-1,-1]
matrix[1, -1]
matrix[1, 2]

5

### Slicing을 알아보자

In [ ]:
matrix = np.array([[0,1,2], [3,4,5]])

In [85]:
# 첫번째 행의 전체
print(matrix[0,])
print(matrix[0, :])

[0 1 2]
[0 1 2]


In [90]:
# 두번째 열의 전체
print(matrix[ : , 1])

[1 4]


In [89]:
# 두번째 행의 두번째 열부터 끝열까지
print(matrix[ 1 , 1 :])

[4 5]


In [91]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [93]:
aryInfo(m)

type : <class 'numpy.ndarray'>
shape : (3, 5) , dimension : 2 , dtype : int32
Array's Data : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [97]:
# 값 7을 인덱싱하라
print(m[1, 2])

7
14
14
14
14


In [98]:
# 값 14를 인덱싱하라
print(m[2, 4])
print(m[2, -1])
print(m[-1, -1])
print(m[-1, 4])

14
14
14
14


In [102]:
# 배열 [6, 7]을 슬라이싱하라
print(m[1, 1:3])

[6 7]


In [126]:
# 배열 [7, 12]를 슬라이싱하라
print(m[1:3 , 2])
print(m[1:,2])

[ 7 12]
[ 7 12]


In [112]:
# 배열[[3,4], [8,9]]를 슬라이싱하라

print(m[:2, 3:5])

[[3 4]
 [8 9]]


### boolean indexing

In [129]:
odd_even = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
aryInfo(odd_even)

type : <class 'numpy.ndarray'>
shape : (10,) , dimension : 1 , dtype : int32
Array's Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [130]:
odd_even[idx] # True로 매칭되는 데이터만 출력

array([0, 2, 4, 6, 8])

In [135]:
odd_even[odd_even % 2 == 0]

array([0, 2, 4, 6, 8])

In [136]:
odd_even % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

### fancing Indexing

In [137]:
data = np.array([1,2,3,4,5,6,7,8,9])
idx = np.array([0, 2, 4, 6, 8]) #index의 번지수를 의미
data[idx]

array([1, 3, 5, 7, 9])

In [138]:
idx = np.array([0,0,0,1,1,1,2,2,2]) #배열 요소의 크기와 상관이 없음
data[idx]

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [139]:
n_dim_ary = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
aryInfo(n_dim_ary)

type : <class 'numpy.ndarray'>
shape : (3, 4) , dimension : 2 , dtype : int32
Array's Data : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [146]:
n_dim_ary[:, [0, 3]] #배열 indexing 이용하여 가져올 수도 있다.

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [149]:
n_dim_ary[: , [True, False, False, True]] #boolean indexing을 이용한 방법

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [150]:
idx = np.array([0, 3])
n_dim_ary[: , idx]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [154]:
n_dim_ary[[-1, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [155]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [156]:
aryInfo(x)

type : <class 'numpy.ndarray'>
shape : (20,) , dimension : 1 , dtype : int32
Array's Data : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [165]:
# 3의 배수를 찾아라
print(x[x % 3 == 0])
# 4로 나눴을 때 나머지가 1인 수를 찾아라
print(x[x % 4 == 1])
# 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라
print(x[(x % 3 == 0) & (x % 4 == 1)], type(x[(x % 3 == 0) & (x % 4 == 1)])) # [9]가 list가 아님, ndarray이 타입이다.

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9] <class 'numpy.ndarray'>


###  배열의 생성과 변형

In [172]:
ary = np.arange(0,12,1).reshape(3,4) # arange는 1차원 배열을 만드는데 reshape을 통해 원하는 형태로 배열을 만들 수 있다.
aryInfo(ary)

type : <class 'numpy.ndarray'>
shape : (3, 4) , dimension : 2 , dtype : int32
Array's Data : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [179]:
# 10을 찾고자 한다면..?
print(ary[2, 2], type(ary[2,2]))

# 6을 찾고자 한다면..?
print(ary[1, 2], type(ary[1,2]))
print(ary[1:2, 2], type(ary[1:2, 2]))

# 5를 찾고자 한다면..?
print(ary[1:2, 1:2], type(ary[1:2, 1:2]))

10 <class 'numpy.int32'>
6 <class 'numpy.int32'>
[6] <class 'numpy.ndarray'>
[[5]] <class 'numpy.ndarray'>


ndarray가 포함하고 있는 것
- vector(1차원 - 배열) - pandas(Series)
- Matrix(N차원 - 행렬) - pandas(DataFrame)

In [185]:
print(ary[ : , [0, 2]], type(ary[ : , [0, 2]]))

[[ 0  2]
 [ 4  6]
 [ 8 10]] <class 'numpy.ndarray'>


In [190]:
# 2 와 10을 가져와보고 싶다? --> 결과값은 똑같지만 출력 결과 차원이 다르다.
aryInfo(ary[[0,2] , 2]) # 1차원 출력
aryInfo(ary[[0,2] , 2:3]) # 2차원 출력

type : <class 'numpy.ndarray'>
shape : (2,) , dimension : 1 , dtype : int32
Array's Data : 
 [ 2 10]
type : <class 'numpy.ndarray'>
shape : (2, 1) , dimension : 2 , dtype : int32
Array's Data : 
 [[ 2]
 [10]]


In [234]:
# 0, 8 , 2, 10을 2차원의 배열 형식으로 가져온다면?
# [[0 2]
#  [8 10]]

print(aryInfo(ary[[0, 2], [0, 2]])) # 초기 생각 --> 원하는 결과가 나오지 않음
print('*'*50)

# np.ix_ 를 이용한 해결 즉, 인덱스를 활용했을 때
print('np.ix_() --->')
print(ary[ np.ix_([0,2], [0,2])])
print('*'*50)

rowIdx = np.array([0,2])
print('rowIdx : ', rowIdx)
colIdx = np.array([0,2])
print('colIdx : ', colIdx)
print('*'*50)


print(ary[[rowIdx]])
print('*'*50)
print(ary[[rowIdx]] [: , colIdx])

type : <class 'numpy.ndarray'>
shape : (2,) , dimension : 1 , dtype : int32
Array's Data : 
 [ 0 10]
None
**************************************************
np.ix_() --->
[[ 0  2]
 [ 8 10]]
**************************************************
rowIdx :  [0 2]
colIdx :  [0 2]
**************************************************
[[ 0  1  2  3]
 [ 8  9 10 11]]
**************************************************
[[ 0  2]
 [ 8 10]]


<ipython-input-234-d12ce9c011ad>:20: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print(ary[[rowIdx]])
<ipython-input-234-d12ce9c011ad>:22: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print(ary[[rowIdx]] [: , colIdx])


In [228]:
print('*'*50)
print(aryInfo(ary[[0, 2] , ::2]))

**************************************************
type : <class 'numpy.ndarray'>
shape : (2, 2) , dimension : 2 , dtype : int32
Array's Data : 
 [[ 0  2]
 [ 8 10]]
None


In [235]:
x = np.array([1,2,3] , dtype='U')
aryInfo(x)

type : <class 'numpy.ndarray'>
shape : (3,) , dimension : 1 , dtype : <U1
Array's Data : 
 ['1' '2' '3']


In [236]:
x[0] + x[1] # 문자열로 형 변환을 했기 때문에 1과 2를 붙인 12가 출력

'12'

In [237]:
x = np.array([1,2,3] , dtype='f')
aryInfo(x)

type : <class 'numpy.ndarray'>
shape : (3,) , dimension : 1 , dtype : float32
Array's Data : 
 [1. 2. 3.]


In [240]:
x[0] + x[1] # float로 형변환을 했기 때문에 3.0 출력

3.0

표현 속성
- inf : 무한대를 표현할 때 쓰는 속성 (np.innf(infinity))
- NaN : 정의할 수 없는 숫자 (np.nan(not a number))

In [241]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

<ipython-input-241-6ab12ec6e7a4>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
<ipython-input-241-6ab12ec6e7a4>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

### 배열 생성시 사용할 수 있는 함수
- array()
- arange()
- zeros(), ones()
- zeros_like(), ones_like()
- empty()
- linspace

In [247]:
z = np.zeros(5)
aryInfo(z)

type : <class 'numpy.ndarray'>
shape : (5,) , dimension : 1 , dtype : float64
Array's Data : 
 [0. 0. 0. 0. 0.]


In [250]:
z = np.zeros((5,2), dtype='i')
aryInfo(z)

type : <class 'numpy.ndarray'>
shape : (5, 2) , dimension : 2 , dtype : int32
Array's Data : 
 [[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [252]:
o = np.ones((2, 3 ,4), dtype = 'i')
aryInfo(o)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4) , dimension : 3 , dtype : int32
Array's Data : 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [254]:
zl = np.zeros_like(z, dtype='f')
aryInfo(zl)

type : <class 'numpy.ndarray'>
shape : (5, 2) , dimension : 2 , dtype : float32
Array's Data : 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [257]:
zl = np.ones_like(z, dtype='f')
aryInfo(zl)

type : <class 'numpy.ndarray'>
shape : (5, 2) , dimension : 2 , dtype : float32
Array's Data : 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [261]:
e = np.empty((4,3))
aryInfo(e)

type : <class 'numpy.ndarray'>
shape : (4, 3) , dimension : 2 , dtype : float64
Array's Data : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [262]:
np.arange(10) # 0....n-1 까지 값 출력

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [264]:
np.arange(3, 21, 2) # 시작, 끝(포함하지 않는다), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [265]:
np.linspace(0, 100, 5) # 100을 5개의 구간으로 분리하겠다.


array([  0.,  25.,  50.,  75., 100.])

- 전치행렬(transpose matrix)
- 행렬의 행은 열로, 열은 행으로 바꾼 행렬을 의미한다.
- T (속성)

In [266]:
ary = np.array([ [1,2,3] , [4,5,6] ])

In [268]:
ary_t = ary.T
aryInfo(ary_t)

type : <class 'numpy.ndarray'>
shape : (3, 2) , dimension : 2 , dtype : int32
Array's Data : 
 [[1 4]
 [2 5]
 [3 6]]


In [278]:
# vector 에 transpose가 가능할까?
vec = np.arange(10)
aryInfo(vec)
print('*'*50)

vec_t = vec.T
aryInfo(vec_t)
print('*'*50)

vec_r_t = vec.reshape(1, 10).T
aryInfo(vec_r_t)

type : <class 'numpy.ndarray'>
shape : (10,) , dimension : 1 , dtype : int32
Array's Data : 
 [0 1 2 3 4 5 6 7 8 9]
**************************************************
type : <class 'numpy.ndarray'>
shape : (10,) , dimension : 1 , dtype : int32
Array's Data : 
 [0 1 2 3 4 5 6 7 8 9]
**************************************************
type : <class 'numpy.ndarray'>
shape : (10, 1) , dimension : 2 , dtype : int32
Array's Data : 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


### 크기 변형


In [280]:
x = np.arange(12)
aryInfo(x)

type : <class 'numpy.ndarray'>
shape : (3, 4) , dimension : 2 , dtype : int32
Array's Data : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [283]:
xx = x.reshape(3,4)
aryInfo(xx)

type : <class 'numpy.ndarray'>
shape : (3, 4) , dimension : 2 , dtype : int32
Array's Data : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [291]:
x_reshape = x.reshape(2, -1) #row가 결정이 됐으면 내부 요소에 따라서 col이 알아서 맞춰준다.
aryInfo(x_reshape)

type : <class 'numpy.ndarray'>
shape : (2, 2, 3) , dimension : 3 , dtype : int32
Array's Data : 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [292]:
x_reshape = x.reshape(2, -1, 2) # (depth, row, col)
aryInfo(x_reshape)

type : <class 'numpy.ndarray'>
shape : (2, 3, 2) , dimension : 3 , dtype : int32
Array's Data : 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
