### 배열 확장
- hstack : horizental stack
- vstack : vertical stack
- dstack : depth stack
- stack
- r_
- c_
- tile

In [2]:
import numpy as np

In [3]:
def aryInfo(arr) :
    print("type : {}".format(type(arr)))
    print("shape : {} , dimension : {} , dtype : {}".format(arr.shape , arr.ndim, arr.dtype))
    print("Array's Data : \n" , arr)

In [7]:
# hstack : col이 늘어나는 것이기 때문에 반드시 행의 숫자가 똑같아야만 한다.
h_ary_01 = np.ones((2,3))
aryInfo(h_ary_01)

type : <class 'numpy.ndarray'>
shape : (2, 3) , dimension : 2 , dtype : float64
Array's Data : 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# astype() : 타입의 변화를 줄 때 사용하는 방법 중 하나, dtype=''도 있다. 
re_type = h_ary_01.astype(np.int32)
aryInfo(re_type)

type : <class 'numpy.ndarray'>
shape : (2, 3) , dimension : 2 , dtype : int32
Array's Data : 
 [[1 1 1]
 [1 1 1]]


In [11]:
h_ary_02 = np.zeros((2,3))
aryInfo(h_ary_02)

type : <class 'numpy.ndarray'>
shape : (2, 3) , dimension : 2 , dtype : float64
Array's Data : 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
np.hstack([h_ary_01, h_ary_02])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [ ]:
# vstack : row가 늘어나는 것이기 때문에 반드시 열의 숫자가 똑같아야만 한다.

In [14]:
np.vstack([h_ary_01, h_ary_02]) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# dstack : 깊이가 늘어나는 것
d_ary_01 = np.ones((3,4))
print(d_ary_01)
d_ary_02 = np.zeros((3,4))
print(d_ary_02)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
# (3 * 4) --> (3 * 4 * 2)
np.dstack([d_ary_01, d_ary_02])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [21]:
aryInfo(np.dstack([d_ary_01, d_ary_02]))

type : <class 'numpy.ndarray'>
shape : (3, 4, 2) , dimension : 3 , dtype : float64
Array's Data : 
 [[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]


In [29]:
s_ary = np.stack([d_ary_01, d_ary_02], axis=0)
aryInfo(s_ary)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4) , dimension : 3 , dtype : float64
Array's Data : 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [30]:
s_ary = np.stack([d_ary_01, d_ary_02], axis=1)
aryInfo(s_ary)

type : <class 'numpy.ndarray'>
shape : (3, 2, 4) , dimension : 3 , dtype : float64
Array's Data : 
 [[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]


In [31]:
s_ary = np.stack([d_ary_01, d_ary_02], axis=2)
aryInfo(s_ary)

type : <class 'numpy.ndarray'>
shape : (3, 4, 2) , dimension : 3 , dtype : float64
Array's Data : 
 [[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]
