# Numpy

## 학습목표 : 배열과 리스트의 차이점을 배워보자

In [7]:
import numpy as np

In [8]:
np.__version__

'1.19.2'

### 배열 자료구조 클래스인 ndarray - vector , matrix
### 배열의 차원과 크기 - ndim , shape

In [12]:
def aryInfo(arr) :
    print("type : {}".format(type(arr)))
    print("shape : {} , dimension : {} , dtype : {}".format(arr.shape , arr.ndim, arr.dtype))
    print("Array's Data : \n" , arr)

### 1차원 배열 만들기

In [13]:
ary = np.array([0,1,2,3,4,5,6,7,8,9])
ary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
aryInfo(ary)

type : <class 'numpy.ndarray'>
shape : (10,) , dimension : 1 , dtype : int32
Array's Data : 
 [0 1 2 3 4 5 6 7 8 9]


### Vectorized Operation( 벡터화 연산 )

In [23]:
data = [0,1,2,3,4,5,6,7,8,9]
data * 2 # 리스트 자체로는 계산이 불가능하다. list comprehension 이나 for loop 활용해야 한다. 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
# for 문을 활용한 의도한 계산법
answer = []
for d in data :
    answer.append(d * 2)
print(answer, type(data))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18] <class 'list'>


In [28]:
# list comprehension을 이용한 계싼법
data2 = [i*2 for i in data]
print(data2, type(data2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18] <class 'list'>


In [27]:
# 벡터화 연산을 이용한 빠른 연산이 가능하다. 반복을 사용했을 때 보다 수행의 속도가 빠르고 메모리 절감!
x = np.array(data)
x * 2
print(x, type(x))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


### 비교연산, 논리연산

In [33]:
oneAry = np.array([1,2,3])
twoAry = np.array([10,20,30])
oneAry + twoAry

array([11, 22, 33])

In [34]:
oneAry + twoAry * 2

array([21, 42, 63])

In [35]:
# boolean 형식으로 값이 들어있는지 확인가능 boolean masking
oneAry == 2

array([False,  True, False])

In [36]:
twoAry > 10

array([False,  True,  True])

In [37]:
(oneAry == 2) & (twoAry > 10)

array([False,  True, False])

### 2차원 배열 (행렬, matrix)

In [38]:
matrix = np.array([[0,1,2], [3,4,5]])
aryInfo(matrix)

type : <class 'numpy.ndarray'>
shape : (2, 3) , dimension : 2 , dtype : int32
Array's Data : 
 [[0 1 2]
 [3 4 5]]


In [40]:
print('행의 갯수 : ', len(matrix))
print('열의 갯수 : ', len(matrix[0]))

행의 갯수 :  2
열의 갯수 :  3


### 3차원 배열

In [46]:
threeDimAry = np.array([[[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12]],
                        [[11,12,13,14],
                        [15,16,17,18],
                        [19,20,21,22]]])

In [47]:
aryInfo(threeDimAry)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4) , dimension : 3 , dtype : int32
Array's Data : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [51]:
print( len(threeDimAry) , len(threeDimAry[0]) , len(threeDimAry[0][0]))

2 3 4


In [55]:
x = np.array([100, 'hello', 3.14])
x
# <U11 type은 문자열이라고 생각하면 된다.
print('array {}'.format(x))
print('type {}'.format(type(x)))
print('x.type {}'.format(x.dtype))
print('x[0] type {}'.format(type(x[0])))

array ['100' 'hello' '3.14']
type <class 'numpy.ndarray'>
x.type <U11
x[0] type <class 'numpy.str_'>


### indexing를 알아보자

In [54]:
data = np.array([0,1,2,3,4,5])
aryInfo(data)

type : <class 'numpy.ndarray'>
shape : (6,) , dimension : 1 , dtype : int32
Array's Data : 
 [0 1 2 3 4 5]


In [56]:
data[2]

2

In [58]:
data[-1]

5

In [59]:
matrix = np.array([[0,1,2], [3,4,5]])
aryInfo(matrix)

type : <class 'numpy.ndarray'>
shape : (2, 3) , dimension : 2 , dtype : int32
Array's Data : 
 [[0 1 2]
 [3 4 5]]


In [74]:
matrix[-1,-1]
matrix[1, -1]
matrix[1, 2]

5

### Slicing을 알아보자

In [ ]:
# 첫번째 행의 전체
# 두번째 열의 전체
# 두번째 행의 두번째 열부터 끝열까지

In [ ]:
matrix = np.array([[0,1,2], [3,4,5]])

In [85]:
# 첫번째 행의 전체
print(matrix[0,])
print(matrix[0, :])

[0 1 2]
[0 1 2]


In [90]:
# 두번째 열의 전체
print(matrix[ : , 1])

[1 4]


In [89]:
# 두번째 행의 두번째 열부터 끝열까지
print(matrix[ 1 , 1 :])

[4 5]
