numpy 모듈을 import 해서 np라는 약어로 사용한다.

In [3]:
import numpy as np

이후 만들어 볼 배열들의 특징을 간편하게 확인하기 위해 함수를 정의해보자.

In [4]:
def aryInfo(array) :
    print("type : {}".format(type(array)))
    print("shape : {}, dimension : {}, dtype : {}".format(array.shape, array.ndim, array.dtype))
    print("Array's Data : \n", array)

1차원 배열 생성하기

In [5]:
array = np.array([0,1,2,3,4,5,6,7,8,9])
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

생성한 aryInfo 함수를 사용하여 만들어 본 1차원 배열의 특징을 살펴보자

In [7]:
aryInfo(array)

type : <class 'numpy.ndarray'>
shape : (10,), dimension : 1, dtype : int32
Array's Data : 
 [0 1 2 3 4 5 6 7 8 9]


벡터화 연산 (Vectorized Operation)

In [8]:
data = [0,1,2,3,4,5,6,7,8,9]
# 리스트 자체로는 계산이 불가능하다. --> list comprehension이나 for loop를 활용해야 한다.
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
# for 문을 활용한 의도한 계산법
answer = []

for i in data :
    answer.append(i * 2)
print(answer)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [12]:
# list comprehension을 활용한 의도한 계산법
answer = [i*2 for i in data]
print(answer)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [15]:
# 벡터화 연산을 이용하면 빠른 연산이 가능하다. 반복을 사용했을 때 보다 수행의 속도가 빠르고 메모리 절감효과
x = np.array(data)
answer = x * 2
print(answer, type(answer))

[ 0  2  4  6  8 10 12 14 16 18] <class 'numpy.ndarray'>
