In [1]:
import numpy as np

In [9]:
def aryInfo(arr):
    print("type : {}".format(type(arr)))
    print("shape : {}, dimension : {}, dtype : {}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data : \n", arr)

In [4]:
data = np.loadtxt('./data/ratings.dat' , delimiter = "::", dtype=np.int64)

In [10]:
# 데이터 헤딩 user_id , movie_id, rating, timestamp
aryInfo(data)

type : <class 'numpy.ndarray'>
shape : (1000209, 4), dimension : 2, dtype : int64
Array's Data : 
 [[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


In [12]:
# 데이터의 첫 5 행만 확인
data[ :5, : ]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [15]:
# 데이터의 형태 확인
print(aryInfo(data))
print(data.shape)
print(data.ndim)
print(data.dtype)

type : <class 'numpy.ndarray'>
shape : (1000209, 4), dimension : 2, dtype : int64
Array's Data : 
 [[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]
None
(1000209, 4)
2
int64


In [20]:
# 전체 평점 평균 계산
m_rating_total = data[ : , 2].mean()
m_rating_total

3.581564453029317

In [23]:
m_rating_total2 = np.mean(data[ : , 2])
m_rating_total2

3.581564453029317

In [27]:
# 사용자 아이디 수집
# np.unique()를 사용하면 될까?
np.unique(data[ : , 0])

array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [34]:
# 사용자별 평점 확인을 위한 코드 구문 작성
user_ids = data[:, 0]
user_input = input("user_id를 입력하세요")
for user_id in user_ids:
    if user_id == user_input:
        check = np.vstack([data[i] for i in range(data.shape[0])])
        print(check)

user_id를 입력하세요1


(1000209,)

In [ ]:
#np.savetext('xxx.csv, xxxxx , fmt='%.1f', delimiter=',')